name: Agents CI

on:
  push:
  pull_request:

jobs:
  check-format:
    name: Agents format checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run format check
        working-directory: agents
        run: make check-format

  lint:
    name: Agents linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linter
        working-directory: agents
        run: make lint
